// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pdouelle.GenericRepository.Api.Debug.Data;

namespace douell_p.GenericRepository.Api.Debug.Migrations
{
    [DbContext(typeof(DatabaseService))]
    [Migration("20210428140221_initial_migration")]
    partial class initial_migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("douell_p.GenericRepository.Api.Debug.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("WeatherForecastId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WeatherForecastId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("douell_p.GenericRepository.Api.Debug.Entities.WeatherForecast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts");
                });

            modelBuilder.Entity("douell_p.GenericRepository.Api.Debug.Entities.Location", b =>
                {
                    b.HasOne("douell_p.GenericRepository.Api.Debug.Entities.WeatherForecast", "WeatherForecast")
                        .WithMany("Locations")
                        .HasForeignKey("WeatherForecastId");

                    b.Navigation("WeatherForecast");
                });

            modelBuilder.Entity("douell_p.GenericRepository.Api.Debug.Entities.WeatherForecast", b =>
                {
                    b.Navigation("Locations");
                });
#pragma warning restore 612, 618
        }
    }
}
